
---
events:
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineSystem.cmake:233 (message)"
      - "CMakeLists.txt:53 (project)"
    message: |
      The system is: Windows - 10.0.19045 - AMD64
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCCompiler.cmake:123 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:53 (project)"
    message: |
      Compiling the C compiler identification source file "CMakeCCompilerId.c" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 pour .NET Framework
      Copyright (C) Microsoft Corporation. Tous droits réservés.
      
      La génération a démarré 04/07/2024 18:29:08.
      Projet "C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.vcxproj" sur le noud 1 (cibles par défaut).
      PrepareForBuild:
        Création du répertoire "Debug\\".
        Création du répertoire "Debug\\CompilerIdC.tlog\\".
      InitializeBuildStatus:
        Création de "Debug\\CompilerIdC.tlog\\unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TC /analyze- /FC /errorReport:queue CMakeCCompilerId.c
        CMakeCCompilerId.c
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdC.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdC.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdC.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCCompilerId.obj
        CompilerIdC.vcxproj -> C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\3.28.1\\CompilerIdC\\.\\CompilerIdC.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_C_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_C_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx86\\x86\\cl.exe
      FinalizeBuildStatus:
        Suppression du fichier "Debug\\CompilerIdC.tlog\\unsuccessfulbuild".
        Mise à jour de l'horodatage "Debug\\CompilerIdC.tlog\\CompilerIdC.lastbuildstate".
      Génération du projet "C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\3.28.1\\CompilerIdC\\CompilerIdC.vcxproj" terminée (cibles par défaut).
      
      La génération a réussi.
          0 Avertissement(s)
          0 Erreur(s)
      
      Temps écoulé 00:00:01.19
      
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.exe"
      
      Compilation of the C compiler identification source "CMakeCCompilerId.c" produced "CompilerIdC.vcxproj"
      
      The C compiler identification is MSVC, found in:
        C:/Work/VoIP/N_projects/Saylo/linphone-desktop/build/CMakeFiles/3.28.1/CompilerIdC/CompilerIdC.exe
      
  -
    kind: "message-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:17 (message)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerId.cmake:64 (__determine_compiler_id_test)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCXXCompiler.cmake:126 (CMAKE_DETERMINE_COMPILER_ID)"
      - "CMakeLists.txt:53 (project)"
    message: |
      Compiling the CXX compiler identification source file "CMakeCXXCompilerId.cpp" succeeded.
      Compiler:  
      Build flags: 
      Id flags:  
      
      The output was:
      0
      Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 pour .NET Framework
      Copyright (C) Microsoft Corporation. Tous droits réservés.
      
      La génération a démarré 04/07/2024 18:29:10.
      Projet "C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" sur le noud 1 (cibles par défaut).
      PrepareForBuild:
        Création du répertoire "Debug\\".
        Création du répertoire "Debug\\CompilerIdCXX.tlog\\".
      InitializeBuildStatus:
        Création de "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
      ClCompile:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /nologo /W0 /WX- /diagnostics:classic /Od /Oy- /D _MBCS /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"Debug\\\\" /Fd"Debug\\vc141.pdb" /Gd /TP /analyze- /FC /errorReport:queue CMakeCXXCompilerId.cpp
        CMakeCXXCompilerId.cpp
      Link:
        C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:".\\CompilerIdCXX.exe" /INCREMENTAL:NO /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib comdlg32.lib advapi32.lib shell32.lib ole32.lib oleaut32.lib uuid.lib odbc32.lib odbccp32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /PDB:".\\CompilerIdCXX.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:".\\CompilerIdCXX.lib" /MACHINE:X86 /SAFESEH Debug\\CMakeCXXCompilerId.obj
        CompilerIdCXX.vcxproj -> C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\3.28.1\\CompilerIdCXX\\.\\CompilerIdCXX.exe
      PostBuildEvent:
        for %%i in (cl.exe) do @echo CMAKE_CXX_COMPILER=%%~$PATH:i
        :VCEnd
        CMAKE_CXX_COMPILER=C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\Hostx86\\x86\\cl.exe
      FinalizeBuildStatus:
        Suppression du fichier "Debug\\CompilerIdCXX.tlog\\unsuccessfulbuild".
        Mise à jour de l'horodatage "Debug\\CompilerIdCXX.tlog\\CompilerIdCXX.lastbuildstate".
      Génération du projet "C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\3.28.1\\CompilerIdCXX\\CompilerIdCXX.vcxproj" terminée (cibles par défaut).
      
      La génération a réussi.
          0 Avertissement(s)
          0 Erreur(s)
      
      Temps écoulé 00:00:00.82
      
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.exe"
      
      Compilation of the CXX compiler identification source "CMakeCXXCompilerId.cpp" produced "CompilerIdCXX.vcxproj"
      
      The CXX compiler identification is MSVC, found in:
        C:/Work/VoIP/N_projects/Saylo/linphone-desktop/build/CMakeFiles/3.28.1/CompilerIdCXX/CompilerIdCXX.exe
      
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:53 (project)"
    checks:
      - "Detecting C compiler ABI info"
    directories:
      source: "C:/Work/VoIP/N_projects/Saylo/linphone-desktop/build/CMakeFiles/CMakeScratch/TryCompile-cknk26"
      binary: "C:/Work/VoIP/N_projects/Saylo/linphone-desktop/build/CMakeFiles/CMakeScratch/TryCompile-cknk26"
    cmakeVariables:
      CMAKE_C_FLAGS: "/DWIN32 /D_WINDOWS /W3"
    buildResult:
      variable: "CMAKE_C_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Work/VoIP/N_projects/Saylo/linphone-desktop/build/CMakeFiles/CMakeScratch/TryCompile-cknk26'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe" cmTC_ea963.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:n
        Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 pour .NET Framework
        Copyright (C) Microsoft Corporation. Tous droits réservés.
        
        La génération a démarré 04/07/2024 18:29:11.
        Projet "C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\CMakeScratch\\TryCompile-cknk26\\cmTC_ea963.vcxproj" sur le noud 1 (cibles par défaut).
        PrepareForBuild:
          Création du répertoire "cmTC_ea963.dir\\Debug\\".
          Création du répertoire "C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\CMakeScratch\\TryCompile-cknk26\\Debug\\".
          Création du répertoire "cmTC_ea963.dir\\Debug\\cmTC_ea963.tlog\\".
        InitializeBuildStatus:
          Création de "cmTC_ea963.dir\\Debug\\cmTC_ea963.tlog\\unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_ea963.dir\\Debug\\\\" /Fd"cmTC_ea963.dir\\Debug\\vc141.pdb" /Gd /TC /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          Compilateur d'optimisation Microsoft (R) C/C++ version 19.16.27051 pour x86
          Copyright (C) Microsoft Corporation. Tous droits réservés.
          
          cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /Fo"cmTC_ea963.dir\\Debug\\\\" /Fd"cmTC_ea963.dir\\Debug\\vc141.pdb" /Gd /TC /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCCompilerABI.c"
          
          CMakeCCompilerABI.c
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\CMakeScratch\\TryCompile-cknk26\\Debug\\cmTC_ea963.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Work/VoIP/N_projects/Saylo/linphone-desktop/build/CMakeFiles/CMakeScratch/TryCompile-cknk26/Debug/cmTC_ea963.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Work/VoIP/N_projects/Saylo/linphone-desktop/build/CMakeFiles/CMakeScratch/TryCompile-cknk26/Debug/cmTC_ea963.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_ea963.dir\\Debug\\CMakeCCompilerABI.obj
          cmTC_ea963.vcxproj -> C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\CMakeScratch\\TryCompile-cknk26\\Debug\\cmTC_ea963.exe
        FinalizeBuildStatus:
          Suppression du fichier "cmTC_ea963.dir\\Debug\\cmTC_ea963.tlog\\unsuccessfulbuild".
          Mise à jour de l'horodatage "cmTC_ea963.dir\\Debug\\cmTC_ea963.tlog\\cmTC_ea963.lastbuildstate".
        Génération du projet "C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\CMakeScratch\\TryCompile-cknk26\\cmTC_ea963.vcxproj" terminée (cibles par défaut).
        
        La génération a réussi.
            0 Avertissement(s)
            0 Erreur(s)
        
        Temps écoulé 00:00:01.03
        
      exitCode: 0
  -
    kind: "try_compile-v1"
    backtrace:
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeDetermineCompilerABI.cmake:57 (try_compile)"
      - "C:/Program Files/CMake/share/cmake-3.28/Modules/CMakeTestCXXCompiler.cmake:26 (CMAKE_DETERMINE_COMPILER_ABI)"
      - "CMakeLists.txt:53 (project)"
    checks:
      - "Detecting CXX compiler ABI info"
    directories:
      source: "C:/Work/VoIP/N_projects/Saylo/linphone-desktop/build/CMakeFiles/CMakeScratch/TryCompile-6o58ea"
      binary: "C:/Work/VoIP/N_projects/Saylo/linphone-desktop/build/CMakeFiles/CMakeScratch/TryCompile-6o58ea"
    cmakeVariables:
      CMAKE_CXX_FLAGS: "/DWIN32 /D_WINDOWS /W3 /GR /EHsc"
    buildResult:
      variable: "CMAKE_CXX_ABI_COMPILED"
      cached: true
      stdout: |
        Change Dir: 'C:/Work/VoIP/N_projects/Saylo/linphone-desktop/build/CMakeFiles/CMakeScratch/TryCompile-6o58ea'
        
        Run Build Command(s): "C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/MSBuild/15.0/Bin/MSBuild.exe" cmTC_2c9e9.vcxproj /p:Configuration=Debug /p:Platform=Win32 /p:VisualStudioVersion=15.0 /v:n
        Microsoft (R) Build Engine version 15.9.21+g9802d43bc3 pour .NET Framework
        Copyright (C) Microsoft Corporation. Tous droits réservés.
        
        La génération a démarré 04/07/2024 18:29:13.
        Projet "C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\CMakeScratch\\TryCompile-6o58ea\\cmTC_2c9e9.vcxproj" sur le noud 1 (cibles par défaut).
        PrepareForBuild:
          Création du répertoire "cmTC_2c9e9.dir\\Debug\\".
          Création du répertoire "C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\CMakeScratch\\TryCompile-6o58ea\\Debug\\".
          Création du répertoire "cmTC_2c9e9.dir\\Debug\\cmTC_2c9e9.tlog\\".
        InitializeBuildStatus:
          Création de "cmTC_2c9e9.dir\\Debug\\cmTC_2c9e9.tlog\\unsuccessfulbuild", car "AlwaysCreate" a été spécifié.
        ClCompile:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\CL.exe /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_2c9e9.dir\\Debug\\\\" /Fd"cmTC_2c9e9.dir\\Debug\\vc141.pdb" /Gd /TP /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          Compilateur d'optimisation Microsoft (R) C/C++ version 19.16.27051 pour x86
          Copyright (C) Microsoft Corporation. Tous droits réservés.
          
          cl /c /Zi /W3 /WX- /diagnostics:classic /Od /Ob0 /Oy- /D _MBCS /D WIN32 /D _WINDOWS /D "CMAKE_INTDIR=\\"Debug\\"" /Gm- /EHsc /RTC1 /MDd /GS /fp:precise /Zc:wchar_t /Zc:forScope /Zc:inline /GR /Fo"cmTC_2c9e9.dir\\Debug\\\\" /Fd"cmTC_2c9e9.dir\\Debug\\vc141.pdb" /Gd /TP /analyze- /errorReport:queue "C:\\Program Files\\CMake\\share\\cmake-3.28\\Modules\\CMakeCXXCompilerABI.cpp"
          
          CMakeCXXCompilerABI.cpp
        Link:
          C:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Community\\VC\\Tools\\MSVC\\14.16.27023\\bin\\HostX86\\x86\\link.exe /ERRORREPORT:QUEUE /OUT:"C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\CMakeScratch\\TryCompile-6o58ea\\Debug\\cmTC_2c9e9.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Work/VoIP/N_projects/Saylo/linphone-desktop/build/CMakeFiles/CMakeScratch/TryCompile-6o58ea/Debug/cmTC_2c9e9.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Work/VoIP/N_projects/Saylo/linphone-desktop/build/CMakeFiles/CMakeScratch/TryCompile-6o58ea/Debug/cmTC_2c9e9.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_2c9e9.dir\\Debug\\CMakeCXXCompilerABI.obj
          cmTC_2c9e9.vcxproj -> C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\CMakeScratch\\TryCompile-6o58ea\\Debug\\cmTC_2c9e9.exe
        FinalizeBuildStatus:
          Suppression du fichier "cmTC_2c9e9.dir\\Debug\\cmTC_2c9e9.tlog\\unsuccessfulbuild".
          Mise à jour de l'horodatage "cmTC_2c9e9.dir\\Debug\\cmTC_2c9e9.tlog\\cmTC_2c9e9.lastbuildstate".
        Génération du projet "C:\\Work\\VoIP\\N_projects\\Saylo\\linphone-desktop\\build\\CMakeFiles\\CMakeScratch\\TryCompile-6o58ea\\cmTC_2c9e9.vcxproj" terminée (cibles par défaut).
        
        La génération a réussi.
            0 Avertissement(s)
            0 Erreur(s)
        
        Temps écoulé 00:00:00.99
        
      exitCode: 0
...
